name: SiriusGameXcodeGenGenerated
options:
    bundleIdPrefix: com.Sirius
    xcodeVersion: "15.4"
    deploymentTarget:
        iOS: "17"
configs:
    Debug: debug
    Release: release
    Staging Debug: debug
    Staging Release: release
configFiles:
    Debug: SiriusProject/SiriusProject/configs/Dev.xcconfig
    Release: SiriusProject/SiriusProject/configs/Dev.xcconfig
    Staging Debug: SiriusProject/SiriusProject/configs/Staging.xcconfig
    Staging Release: SiriusProject/SiriusProject/configs/Staging.xcconfig
schemes:
    SiriusProject Staging:
        build:
            targets:
                SiriusProject: all
                SiriusProjectTests: [test]
        run:
            config: Staging Debug
            
        test:
            config: Staging Debug
            targets:
                - name: SiriusProjectTests
            gatherCoverageData: true
            coverageTargets:
                - SiriusProject
        profile:
            config: Staging Release
        analyze:
            config: Staging Debug
        archive:
            config: Staging Release
settings:
    GENERATE_INFOPLIST_FILE: NO
targets:
    SiriusProject:
        platform: iOS
        type: application
        deploymentTarget: "17"
        sources: ["SiriusProject"]
        capabilities:
            - push-notifications

        attributes:
            SystemCapabilities:
                com.apple.Push:
                    enabled: 1
        settings:
          base:
            INFOPLIST_FILE: "SiriusProject/SiriusProject/Info.plist"
            CODE_SIGN_IDENTITY: "Apple Development: Aleksey Kobyakov (2VHQM6CHHB)"
            PROVISIONING_PROFILE_SPECIFIER: "Provision with push"
            CODE_SIGN_ENTITLEMENTS: SiriusProject/SiriusProject.entitlements

        resources:
            - path: Localizable
    SiriusProjectTests:
        platform: iOS
        type: bundle.unit-test
        deploymentTarget: "17"
        sources: ["SiriusProjectTests"]
        dependencies:
            - target: SiriusProject
        settings:
          base:
            INFOPLIST_FILE: "SiriusProject/SiriusProject/Info.plist"
            CODE_SIGN_IDENTITY: "Apple Development: Aleksey Kobyakov (2VHQM6CHHB)"
