name: SiriusGameXcodeGenGenerated
options:
    bundleIdPrefix: com.Sirius
    xcodeVersion: "15.4"
    deploymentTarget:
        iOS: "17"
configs:
    Debug: debug
    Release: release
    Staging Debug: debug
    Staging Release: release
configFiles:
    Debug: SiriusProject/SiriusProject/configs/Dev.xcconfig
    Release: SiriusProject/SiriusProject/configs/Dev.xcconfig
    Staging Debug: SiriusProject/SiriusProject/configs/Staging.xcconfig
    Staging Release: SiriusProject/SiriusProject/configs/Staging.xcconfig
schemes:
    SiriusProject Staging:
        build:
            targets:
                SiriusProject: all
        run:
            config: Staging Debug
            
        test:
            config: Staging Debug
            gatherCoverageData: true
            coverageTargets:
                - SiriusProject
        profile:
            config: Staging Release
        analyze:
            config: Staging Debug
        archive:
            config: Staging Release
settings:
    GENERATE_INFOPLIST_FILE: NO
targets:
    SiriusProject:
        platform: iOS
        type: application
        deploymentTarget: "17"
        sources: ["SiriusProject"]
<<<<<<< HEAD
        capabilities:
            - push-notifications
=======
>>>>>>> 484e411 (Изменил реализацию Airdrop. Разделил на экран получения и экран отправки (для пользователя/судьи соответственно))
        attributes:
            SystemCapabilities:
                com.apple.Push:
                    enabled: 1
<<<<<<< HEAD

=======
>>>>>>> 484e411 (Изменил реализацию Airdrop. Разделил на экран получения и экран отправки (для пользователя/судьи соответственно))
        settings:
          CODE_SIGN_ENTITLEMENTS: SiriusProject/Entitlements.entitlements
          base:
            INFOPLIST_FILE: "SiriusProject/SiriusProject/Info.plist"
            CODE_SIGN_IDENTITY: "Apple Development: Aleksey Kobyakov (2VHQM6CHHB)"
            PROVISIONING_PROFILE_SPECIFIER: "Provision with push"
            CODE_SIGN_ENTITLEMENTS: SiriusProject/SiriusProject.entitlements

        resources:
            - path: Localizable
