name: iOS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test iOS App
    runs-on: macos-14
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          cd SiriusProject
          xcodebuild -project "SiriusProject.xcodeproj" \
          -sdk iphoneos \
          -scheme "SiriusProject" \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          clean build
